### ISSUE TITLE
installing p4fpga

### ISSUE THREAD

**Issue by ali64Mon** [p4fpga/p4fpga#30]
Hi,

I have some issues while installing p4fpga.
I can see two projects are required: p4c and p4fpga. Do they need to be in separate directories? or p4c is a sub-directory in p4fpga?

To create the soft-link to p4fpga source code in p4c, there is no sub-directory named  "compiler " in p4fpga directory!  There is no sub-directory named "extensions" in p4c either. do we need to create the sub-directories manually?

**Comment by hanw** [comment]
Hi @ali64Mon, I have updated the top-level readme.md to reflect the current process to build p4fpga.

**Comment by ali64Mon** [comment]
Thanks for your reply. Could you please provide me with an example showing how to work with P4FPGA?
